# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ninfo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x92\x02\n\nStreamInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nsystemtime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\n\n\x02id\x18\x04 \x01(\x05\x12\x0f\n\x07trig_id\x18\x05 \x01(\x05\x12\x0b\n\x03pts\x18\x0f \x01(\x03\x12\x0f\n\x07\x63hannel\x18\x06 \x01(\t\x12\x10\n\x08\x63lock_id\x18\x07 \x01(\t\x12\x10\n\x08\x66ilename\x18\x08 \x01(\t\x12\x14\n\x0csession_name\x18\x0e \x01(\t\x12\r\n\x05width\x18\x10 \x01(\x05\x12\x0e\n\x06height\x18\x11 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STREAMINFO']._serialized_start=80
  _globals['_STREAMINFO']._serialized_end=354
# @@protoc_insertion_point(module_scope)
